apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: adb-non-prod
  namespace: argocd
  labels:
    client: adb
    environment: non-prod
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/CodeByMurali/CDUsingArgoCD.git
      revision: master
      directories:
      - path: adb/apps/*/envs/dev # nonprod/jefferis/poc/apps/
      - path: adb/apps/*/envs/qa
      - path: adb/apps/*/envs/stage
  template:      
    metadata:
      name: 'adb-{{index .path.segments 2}}-{{index .path.segments 4}}'
      labels:
        client: adb
        service: '{{index .path.segments 2}}'
        environment: '{{index .path.segments 4}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/CodeByMurali/CDUsingArgoCD.git
        targetRevision: master
        path: '{{.path.path}}'
      destination:
        name: spoke2.us-east-1.eksctl.io
        namespace: '{{index .path.segments 4}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
        automated:
          prune: true
          selfHeal: true
