---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nx-core-deployment
  annotations:
    codefresh.io/app: nx-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nx-core
  template:
    metadata:
      labels:
        app: nx-core
    spec:
      containers:
      - name: nx-core
        imagePullPolicy: Always
        image: docker.io/kostiscodefresh/simple-env-app:1.0
        ports:
        - containerPort: 8080
