---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cross-asset-deployment
spec:
  template:
    spec:
      containers:
      - name: cross-asset
        image: docker.io/kostiscodefresh/simple-env-app:2.0
