apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../argocd/base

commonLabels:
  tenant: ocbc
  environment: dev

patches:
- target:
    kind: ApplicationSet
  patch: |-
    - op: replace
      path: /metadata/name
      value: ocbc-dev
    - op: replace
      path: /metadata/labels/tenant
      value: ocbc
    - op: replace
      path: /metadata/labels/environment
      value: dev
    - op: replace
      path: /spec/template/metadata/labels/tenant
      value: ocbc
    - op: replace
      path: /spec/template/metadata/labels/environment
      value: dev
    - op: replace
      path: /spec/template/metadata/name
      value: ocbc-{{index .path.segments 2}}-dev
    - op: replace
      path: /spec/template/spec/project
      value: ocbc-dev
    - op: replace
      path: /spec/template/spec/destination/name
      value: spoke-cpe-dev-usw2
    - op: replace
      path: /spec/template/spec/destination/namespace
      value: ocbc-dev
    - op: replace
      path: /spec/generators/0/git/directories/0/path
      value: argocd/apps/*/envs/dev

- target:
    kind: AppProject
  patch: |-
    - op: replace
      path: /metadata/name
      value: ocbc-dev
    - op: replace
      path: /metadata/labels/tenant
      value: ocbc
    - op: replace
      path: /metadata/labels/environment
      value: dev
    - op: replace
      path: /spec/description
      value: "OneView ocbc dev environment"
    - op: replace
      path: /spec/destinations/0/name
      value: spoke-cpe-dev-usw2
    - op: replace
      path: /spec/destinations/0/namespace
      value: ocbc-dev
    - op: add
      path: /metadata/annotations
      value:
        aws-account-id: "987654321098"
