apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ocbc-dev
  namespace: argocd
  labels:
    client: ocbc
    environment: dev
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/CodeByMurali/CDUsingArgoCD.git
      revision: sep-custom-folder
      directories:
      - path: argocd/apps/*/envs/dev      
  template:      
    metadata:
      name: 'ocbc-{{index .path.segments 2}}-{{index .path.segments 4}}'
      labels:
        client: ocbc
        service: '{{index .path.segments 2}}'
        environment: '{{index .path.segments 4}}'
    spec:
      project: ocbc-dev
      source:
        repoURL: https://github.com/CodeByMurali/CDUsingArgoCD.git
        targetRevision: sep-custom-folder
        path: '{{.path.path}}'
        kustomize:
          enableHelm: true
      destination:
        name: spoke2.us-east-1.eksctl.io
        namespace: '{{index .path.segments 4}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
        automated:
          prune: true
          selfHeal: true
