apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kynex-sit
  namespace: argocd
spec:
  description: Kynex SIT environment only
  
  sourceRepos:
  - https://github.com/CodeByMurali/CDUsingArgoCD.git
  - https://github.com/CodeByMurali/gitops-demo.git
  
  destinations:
  - namespace: 'sit'
    name: spoke2.us-east-1.eksctl.io
  
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
