---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fincad-deployment
spec:
  template:
    spec:
      containers:
      - name: fincad
        env:
        - name: ENV
          value: "qa"
        - name: GPU_ENABLED
          value: "1"
      