apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: nginx
  repo: https://charts.bitnami.com/bitnami
  version: 15.0.0      # Specify a fixed version for stability
  releaseName: my-test-nginx
  valuesInline:
    # Minimal "Base" values
    service:
      type: ClusterIP
    resources:
      limits:
        cpu: 100m
        memory: 128Mi