apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- applicationset.yaml
- appproject.yaml

commonLabels:
  deployment-model: kynex
  realm: prod
  managed-by: gitops-platform
