---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nx-core-deployment
spec:
  template:
    spec:
      containers:
      - name: nx-core
        env:
        - name: ENV
          value: "prod-us"
        - name: GPU_ENABLED
          value: "1"
      