apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

helmCharts:
- name: nginx
  repo: https://charts.bitnami.com/bitnami
  version: 15.0.0
  releaseName: my-test-nginx
  valuesFile: values.yaml # This links your env-specific values