---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crossasset-deployment
spec:
  template:
    spec:
      containers:
      - name: crossasset-simple
        image: docker.io/kostiscodefresh/simple-env-app:3.0
