---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: newmicro-deployment
  annotations:
    codefresh.io/app: newmicro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newmicro
  template:
    metadata:
      labels:
        app: newmicro
    spec:
      containers:
      - name: newmicro
        imagePullPolicy: Always
        image: docker.io/kostiscodefresh/simple-env-app:1.0
        ports:
        - containerPort: 8080
