---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: newmicro-deployment
spec:
  template:
    spec:
      containers:
      - name: newmicro
        image: docker.io/kostiscodefresh/simple-env-app:2.0
