---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: newnicro-deployment
spec:
  template:
    spec:
      containers:
      - name: newnicro
        image: docker.io/kostiscodefresh/simple-env-app:2.0
